### PR TITLE
remove nav background and change text color

### PR DESCRIPTION
**Pull request by aadibajpai**
makes it more immersive and fixes mlh banner problem

### CODE REVIEW

**Review by SamLee514 — APPROVED** [review]
Hot and spicey

**Comment by wua3** [comment]
quick q: why are we removing the nav bar?

**Comment by aadibajpai** [comment]
> quick q: why are we removing the nav bar?

check slack, tl;dr it fixes the mlh banner issue and also makes the background more immersive

**Comment by wua3** [comment]
> 
> 
> > quick q: why are we removing the nav bar?
> 
> check slack, tl;dr it fixes the mlh banner issue and also makes the background more immersive

got it, it looks good!

**Review by wua3 — APPROVED** [review]

**Pull request merged**
